### ISSUE TITLE
As a customer, I want to be able to enter a postcode, town or city name to the website to find Branches near that postcode so I can visit that Branch.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#1]
Description:

Customer enters a postcode into the website and it should display the nearest branches in the area. This would be done using the API

Value to user: 

Allows users to see the nearest branches to their given postcode saving them time.

MoSCoW : Must 

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [x] Code is peer-reviewed and follows the project's coding standards.

- [x] Code is well-documented and commented.

### Testing:

- [x] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [x] Create database with relevant information from ATM JSON file.

- [x] Create website to display Santander ATMs/Branches.

- [x] Include option on website for user to enter and search for a specific location.

- [x] Create API to fetch relevant information from database based on the location entered by the user (integrate with website to allow geolocation functionality).

- [x] Using the fetched information from database combined with geolocation, API should provide the functionality to display the nearest Santander branches within a set radius from the location that the user has inputted.

**Comment by Jackson-Stewart** [comment]
ticked progress in task list

**Comment by NicolJohn1** [comment]
Issue has been tested an reviewed by development team
