### ISSUE TITLE
As a Customer, I want the website to not take my location unless authorised so I can protect my privacy.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#11]

**Comment by NicolJohn1** [comment]
## Definition of Done
#### Code Quality:
- [ ] Code is peer-reviewed and follows the project's coding standards.
- [ ] Code is well-documented and commented.

#### Testing:
- [ ] Unit tests are written and pass successfully.
- [ ] Integration tests verify functionality and pass successfully.

#### Documentation:
- [ ] User manuals and guides are updated to reflect new features.
- [ ] Technical documentation is updated.

#### Accessibility:
- [ ] The system meets accessibility standards (e.g., WCAG 2.1).

#### Deployment:
- [ ] The feature is deployed to the staging environment and passes all checks.
- [ ] The feature is deployed to the production environment after final approval

## Task List

#### Development:
- [ ] implement feature on webpage that asks user if the webpage can use their location


#### Testing:
- [ ] test appropriately on multiple browsers 

#### Deployment:
- [ ] deploy to webppage
