### ISSUE TITLE
As a bank executive, I want to be able to view details on user search trends so I can make decisions based on the data.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#13]

**Comment by NicolJohn1** [comment]
## Definition of Done
#### Code Quality:
- [ ] Code is peer-reviewed and follows the project's coding standards.
- [ ] Code is well-documented and commented.

#### Testing:
- [ ] Unit tests are written and pass successfully.
- [ ] Integration tests verify functionality and pass successfully.

#### Documentation:
- [ ] User manuals and guides are updated to reflect new features.
- [ ] Technical documentation is updated.

#### Accessibility:
- [ ] The system meets accessibility standards (e.g., WCAG 2.1).

#### Deployment:
- [ ] The feature is deployed to the staging environment and passes all checks.
- [ ] The feature is deployed to the production environment after final approval

## Task List

#### Development:
- [ ] Add an admin page to website where bank execs can access search trends
- [ ] store search results in this page using appropriate data structures
