### ISSUE TITLE
As a Wheelchair User I want to be able to find a Santander branch with wheelchair access so I can enter the building easily.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#17]

**Comment by NicolJohn1** [comment]
## Definition of Done
#### Code Quality:
- [ ] Code is peer-reviewed and follows the project's coding standards.
- [ ] Code is well-documented and commented.

#### Testing:
- [ ] Unit tests are written and pass successfully.
- [ ] Integration tests verify functionality and pass successfully.

#### Documentation:
- [ ] User manuals and guides are updated to reflect new features.
- [ ] Technical documentation is updated.

#### Accessibility:
- [ ] The system meets accessibility standards (e.g., WCAG 2.1).

#### Deployment:
- [ ] The feature is deployed to the staging environment and passes all checks.
- [ ] The feature is deployed to the production environment after final approval

## Task List

#### Development:
- [ ] populate database with ATM and branch information
- [ ] Develop API to pull info from database and link to webpage
- [ ] Add filter option in search bar on webpage to see wheelchair friendly ATMS and branches
