### ISSUE TITLE
As a Customer, I want to be able to enter a postcode to the website to find ATMs near that location so I can use its services.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#2]
### Description:

Customer should be able to enter a postcode and the website displays all the ATMs in that area using the API

MoSCoW : Must

### Estimated Time

T-Shirt size : L

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [ ] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [ ] Create database with relevant information from ATM JSON file.

- [ ] Create website to display Santander ATMs/Branches.

- [ ] Include option on website for user to enter and search for a specific location.

- [ ] Create API to fetch relevant information from database based on the location entered by the user (integrate with website to allow geolocation functionality).

- [ ] Using the fetched information from database combined with geolocation, API should provide the functionality to display the nearest ATMs within a set radius from the location that the user has inputted.
