### ISSUE TITLE
As a customer I want to be able to ask the voice system questions about ATMs near a location and then get the option to follow a link to Google maps so I can see a route (walking or by transport) to the nearest ATM.  

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#29]
Description:

Customer asks voice system where the closest ATMs are to the specified location and they are then taken to a GPS application to see the route to one from the location.

Value to user: 

Allows users to get routes to ATMs based on a location they specify, without switching applications manually, increasing functionality and efficiency for the customer.

MoSCoW : Should

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [ ] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [ ]  Implement access to voice system on website interface, use an API for this

- [ ]  Allow user to query voice system by replying to keywords for closest ATMs near a location

- [ ] Include pop up link to GPS system to plot route to the ATM
