### ISSUE TITLE
As a Customer I want to be able to use the website to find a Santander Branch near me so I can utilise its services.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#3]
### Description:

MoSCow: Must

Value to user: 

Benefits user as they can see the nearest Santander branch to them saving them time and possibly money.

### Estimated Size:
T-shirt Size : XL

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [x] Code is peer-reviewed and follows the project's coding standards.

- [x] Code is well-documented and commented.

### Testing:

- [x] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [x] Create database with relevant information from branch JSON file.

- [x] Get user location from website using geolocation API

- [x] Create API to fetch relevant information from database based on user's location (integrate with website to allow geolocation functionality).

- [x] Using the fetched information from database combined with geolocation, API should provide the functionality to display the nearest Santander branches within a set radius from user's location.

**Comment by NicolJohn1** [comment]
Issue been tested an reviewed by development team
