### ISSUE TITLE
As a company executive I want the systems to be secure so I can prevent third party access. 

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#31]
Description:
ATM systems should have security features like 2FA or SSO so that only the user accessing their own account can do so, and the information inside is kept private from third parties or possible malicious users like thieves.

Value to user: 

Allows customers to keep their details confidential and in doing so the company can follow GDPR and gain a good image.

MoSCoW : Must

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [ ] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [ ]  
- [ ]  
- [ ]
