### ISSUE TITLE
As a branch manager I want to be able to tell when an ATM has been vandalised so I can report the issue to the authorities.  

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#32]
### Description:
Vandalised ATMs are flagged to branch managers so they can report then issue and fix the ATM.

### Value to user:
Managers can view damaged ATMs which they can then report and act on swiftly so they can get it up and working again as soon as possible

MoSCoW : Should

### Definition of done:
 
- [ ]  Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:
 
- [ ]  Code is peer-reviewed and follows the project's coding standards.

- [ ]  Code is well-documented and commented.

### Testing:
 
- [ ]  Unit tests are written and pass successfully.

- [ ]  Integration tests verify functionality and pass successfully.

### Deployment:

- [ ]  The feature is deployed to the staging environment and passes all checks.

- [ ]  The feature is deployed to the production environment after final approval

### Task List:

- [ ] 

- [ ] 

- [ ]
