### ISSUE TITLE
As a bank executive i want to be able to test the database systems capablities by adding dummy ATM location if we want to expand as a company

### ISSUE THREAD

**Issue by NicolJohn1** [Jackson-Stewart/ac31007-Assignment-Repo#35]
### Description:
Vandalised ATMs are flagged to branch managers so they can report then issue and fix the ATM.

### Value to user:
Managers can view damaged ATMs which they can then report and act on swiftly so they can get it up and working again as soon as possible

MoSCoW : Should

### Definition of done:
 
- [ ]  Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:
 
- [x]  Code is peer-reviewed and follows the project's coding standards.

- [x]  Code is well-documented and commented.

### Testing:
 
- [ ]  Unit tests are written and pass successfully.

- [ ]  Integration tests verify functionality and pass successfully.

### Deployment:

- [x]  The feature is deployed to the staging environment and passes all checks.

- [ ]  The feature is deployed to the production environment after final approval

### Task List:

- [x] #36

- [x] #37

- [x] #38

- [x] #45
