### ISSUE TITLE
As a Customer I want to be able to use the website to find a Santander ATM near my location and display it on the map so I can utilize its services.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#4]
### Description:

MoSCow Values : Must

### Estimated Size
T-shirt Size: XL

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [ ] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [ ] Create database with relevant information from ATM JSON file.

- [ ] Get user location from website using geolocation API

- [ ] Create API to fetch relevant information from database based on user's location (integrate with website to allow geolocation functionality).

- [ ] Using the fetched information from database combined with geolocation, API should provide the functionality to display the nearest ATMs within a set radius from user's location.

**Comment by NicolJohn1** [comment]
Issue has been tested an reviewed by development team
