### ISSUE TITLE
As a customer, I only want to see relevant information at the time, which is necessary to be included, so I can focus on the key information that I need. 

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#41]

**Comment by NicolJohn1** [comment]
Description:

make sure the website is maximised for user experience meaning only relevent info is shown on the webpage

Value to user: 

makes browsing experience easy and seamless 

MoSCoW : Should

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [ ] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [ ]  add list of nearest branches on the webage
