### ISSUE TITLE
As a Customer I want to be able to access the Website on my desktop so I can utilize the features and serve my needs.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#5]
### Description:

MoSCow Values : Must

### Estimated Size:
T-shirt Size : M

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [x] Code is peer-reviewed and follows the project's coding standards.

- [x] Code is well-documented and commented.

### Testing:

- [x] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [x] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [x] Create website to display Santander ATMs/Branches.

- [x] Ensure website interface is user-friendly and readable.

- [x] Include option for user to search for a location or for the website to find the user location usiong the API and geolocation

- [x] API fetches relevant information from database based on the location entered by the user (integrate with website to allow geolocation functionality) or by finding the user's location itself.
