### ISSUE TITLE
As a Customer, I expect the website to follow accessibility guidelines, such as WCAG 2, to ensure that it is usable for people with disabilities.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#7]
### Description:

MoSCoW: Must

### Estimated Size:
T-shirt Size: M

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [ ] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:

- [ ] Review WCAG-2 guidelines

- [ ] Accomodate a feature on the website to allow text size to be adjusted based on user needs
