### ISSUE TITLE
As a Customer I want to be able to filter my searches based on specific things so I can find the one I require that meets my needs.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#8]
### Description:

MoSCow Values : Must

### Estimated Size:
T-shirt Size: M

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [ ] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:
