### ISSUE TITLE
As a Customer I want the website on my mobile device to adjust to the size of my phone with no loss of functionality so I can use the app to the best of its capabilities.

### ISSUE THREAD

**Issue by Jackson-Stewart** [Jackson-Stewart/ac31007-Assignment-Repo#9]
### Description:

MoSCow Values : Must

### Estimated Size:
T-shirt Size: M

### Definition of done:

- [ ] Check with the client to ensure it meets their satisfaction and requirements.

### Code Quality:

- [x] Code is peer-reviewed and follows the project's coding standards.

- [ ] Code is well-documented and commented.

### Testing:

- [ ] Unit tests are written and pass successfully.

- [ ] Integration tests verify functionality and pass successfully.

### Deployment:

- [ ] The feature is deployed to the staging environment and passes all checks.

- [ ] The feature is deployed to the production environment after final approval

### Task List:
